name: Defold
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
collections:
    assets:
        output: true
    authors:
        output: true
    tags:
        output: true
kramdown:
    auto_ids: true
    parse_block_html: true
future: true
sass:
    style: compressed
exclude:
    - update.py
    - README.md
    - serve.sh
    - Pipfile
    - Pipfile.lock
    - CNAME
    - Gemfile
    - Gemfile.lock
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      opengraph_image: "https://www.defold.com/images/social/facebook-share.jpg"
      twitter_image: "https://www.defold.com/images/social/twitter-share.jpg"